#! /usr/bin/env bash

env_str='source activate ATL14;'
prog='/home/besmith4/git_repos/pointCollection/pointCollection/index_glob.py'
#env_str=''

ATL14_dir=$1
ATL11_dir=$2 

# make links
[ -d $ATL14_dir/ATL11 ]  || mkdir $ATL14_dir/ATL11
[ -L $ATL14_dir/global ] || ln -s $ATL11_dir $ATL14_dir/global

> index_queue.txt

# northern hemisphere

hemi_dir=$ATL11_dir/north
index_dir=$hemi_dir/index
hemisphere=1 

[ -d $hemi_dir ] || mkdir $hemi_dir
[ -d $index_dir ] || mkdir $index_dir 


for file in `ls $ATL11_dir/ATL11_????0?_????_???_??.h5`; do
    base=`basename $file`
    [ -L $hemi_dir/$base ] || ln -s $file $hemi_dir
    
    index_file=$index_dir"/"$base
    [ -f $index_file ] && continue
    echo "$env_str pushd $index_dir; python3 $prog  --hemisphere $hemisphere --type ATL11 -g ../$base --index_file $index_file --Relative" >> index_queue.txt    
done


#source activate ATL14; python3 $prog --type h5_geoindex -g "$thedir/index/ATL11*.h5" --index_file $thedir/index/GeoIndex.h5 --dir_root $thedir/index/ --hemisphere $hemisphere

