#! /usr/bin/env bash

source activate ATL14

defaults_file=$1
rm -rf par_run


for step in centers edges corners; do
    
    python3 make_1415_queue.py $step $defaults_file > queue.txt

    pboss.py -s queue.txt
    
    pboss.py -r -p -w

done


