#! /usr/bin/env bash

source activate IS2

defaults_file=$1
rm -rf par_run


for step in centers edges corners; do
    
    python3 make_1415_queue_AA.py $step $defaults_file > queue.txt

    [ -s queue.txt ] || continue
    
    pboss.py -s queue.txt
    
    pboss.py -r -p -w

done


