#! /usr/bin/env bash

source activate IS2

defaults_file=$1
rm -rf par_run

[ -z "$2" ] || region_string="-R $2"
    
for step in centers edges corners; do

    queue_file=`make_ATL1415_queue.py $step $defaults_file $region_string  | grep Wrote | awk '{print $NF}'`



    [ -s $queue_file ] || continue
    
    pboss.py -s $queue_file
    
    pboss.py -r -p -w

    #move the log files to the output directory

    out_dir=`grep "b=" $defaults_file  | awk '{FS="="; print $2}' | tail -1`
    [ -d $out_dir/logs ] || mkdir $out_dir/logs
    mv par_run/logs/* $out_dir
   
done


